// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi_PruebaDemo.Models;

#nullable disable

namespace WebApi_PruebaDemo.Migrations
{
    [DbContext(typeof(PruebademoContext))]
    [Migration("20250711215836_AgregaEliminadoLogicoCliente")]
    partial class AgregaEliminadoLogicoCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi_PruebaDemo.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Cliente");

                    b.Property<string>("Correo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__clientes__3214EC2711F41545");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("WebApi_PruebaDemo.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__producto__3214EC27C9FC63BD");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("WebApi_PruebaDemo.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("Idcliente")
                        .HasColumnType("int")
                        .HasColumnName("IDCliente");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__ventas__3214EC273EE29B0D");

                    b.HasIndex("Idcliente");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("WebApi_PruebaDemo.Models.Ventasitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Cantidad")
                        .HasColumnType("float");

                    b.Property<int>("Idproducto")
                        .HasColumnType("int")
                        .HasColumnName("IDProducto");

                    b.Property<int>("Idventa")
                        .HasColumnType("int")
                        .HasColumnName("IDVenta");

                    b.Property<double?>("PrecioTotal")
                        .HasColumnType("float");

                    b.Property<double?>("PrecioUnitario")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__ventasit__3214EC27D34D9564");

                    b.HasIndex("Idproducto");

                    b.HasIndex("Idventa");

                    b.ToTable("ventasitems", (string)null);
                });

            modelBuilder.Entity("WebApi_PruebaDemo.Models.Venta", b =>
                {
                    b.HasOne("WebApi_PruebaDemo.Models.Cliente", "IdclienteNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("Idcliente")
                        .IsRequired()
                        .HasConstraintName("FK_ventas_clientes");

                    b.Navigation("IdclienteNavigation");
                });

            modelBuilder.Entity("WebApi_PruebaDemo.Models.Ventasitem", b =>
                {
                    b.HasOne("WebApi_PruebaDemo.Models.Producto", "IdproductoNavigation")
                        .WithMany("Ventasitems")
                        .HasForeignKey("Idproducto")
                        .IsRequired()
                        .HasConstraintName("FK_ventasitems_productos");

                    b.HasOne("WebApi_PruebaDemo.Models.Venta", "IdventaNavigation")
                        .WithMany("Ventasitems")
                        .HasForeignKey("Idventa")
                        .IsRequired()
                        .HasConstraintName("FK_ventasitems_ventas");

                    b.Navigation("IdproductoNavigation");

                    b.Navigation("IdventaNavigation");
                });

            modelBuilder.Entity("WebApi_PruebaDemo.Models.Cliente", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("WebApi_PruebaDemo.Models.Producto", b =>
                {
                    b.Navigation("Ventasitems");
                });

            modelBuilder.Entity("WebApi_PruebaDemo.Models.Venta", b =>
                {
                    b.Navigation("Ventasitems");
                });
#pragma warning restore 612, 618
        }
    }
}
